name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  CARGO_TERM_COLOR: always
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          pkg-config \
          libssl-dev \
          libasound2-dev \
          libxkbcommon-dev \
          libwayland-dev \
          libatk1.0-dev \
          libpango1.0-dev \
          libgdk-pixbuf2.0-dev \
          libgtk-3-dev \
          libwebkit2gtk-4.1-dev \
          libsoup-3.0-dev \
          libvulkan-dev \
          libxkbcommon-x11-dev \
    - name: Install Goreleaser
      run: |
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update
        sudo apt install goreleaser

    - name: Install Rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with: 
        rustflags: ""
    - name: Rust cache
      uses: swatinem/rust-cache@v2

    - name: Release
      run: |
        goreleaser release

